#!/usr/bin/env bash

# Fail on first line that fails.
set -e

# Only keep staged files that are added (A), copied (C) or modified (M).
STAGED=$(git --no-pager diff --name-only --cached --diff-filter=ACM)
# Files which are only partly staged (eg. git add --patch).
PATCH_STAGED=$(git --no-pager diff --name-only --diff-filter=ACM $STAGED)
# Files which are fully staged.
FULLY_STAGED=$(comm -23 <(echo "$STAGED" | sort) <(echo "$PATCH_STAGED" | sort))

JS_STAGED=$(grep -E '\.(m?js|m?ts|tsx)$' <<< "$STAGED" | grep -v '^docs/flow-typed/' || true)
SNAPSHOT_STAGED=$(grep -E '\.snap$' <<< "$STAGED" || true)
FORMAT_STAGED=$(grep -E '\.(md|css|scss|js|mjs|ts|mts|tsx|json|json5|yaml|yml|html)$' <<< "$STAGED" | grep -v '^docs/flow-typed/' || true)
FORMAT_FULLY_STAGED=$(grep -E '\.(md|css|scss|js|mjs|ts|mts|tsx|json|json5|yaml|yml|html)$' <<< "$FULLY_STAGED" | grep -v '^docs/flow-typed/' || true)
FLOW_STAGED=$(grep -E '^docs/flow-typed/.*\.js$' <<< "$STAGED" || true)
FLOW_FULLY_STAGED=$(grep -E '^docs/flow-typed/.*\.js$' <<< "$FULLY_STAGED" || true)
TEST_CONFIG_STAGED=$(grep -E '^(package(-lock)?\.json|\.node-version)$' <<< "$STAGED" || true)

# Execute each pre-commit hook.
PROJECT_ROOT=$(git rev-parse --show-toplevel)
GIT_ROOT=$(git rev-parse --git-dir)
HOOKS=$PROJECT_ROOT/$GIT_ROOT/hooks/pre-commit.*

for HOOK in $HOOKS; do
  source "$HOOK"
done
